### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by hebingchang** [SE407-2017/FinalProject-library-seats-reservation#12]
**刚刚，我们和项目经理达成共识，把图书馆的管理系统砍掉了**

![image](https://user-images.githubusercontent.com/7235968/32826804-c848ad78-ca24-11e7-825a-a3e4657dcc24.png)

于是现在整个项目只剩下了**微信小程序**。
项目结束了组长请大家吃鸡

**Comment by mayinghua** [comment]
够狠
