### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by hebingchang** [SE407-2017/FinalProject-library-seats-reservation#13]
### 通知
由于微信小程序严格的**权限限制**（未认证的开发者将不能获取用户的UnionID，而认证开发者要**交一笔钱**），初步计划将微信小程序的所有功能移植到Telegram平台。大家不用担心前期WechatController的工作前功尽弃，事实上有很多函数只需改一个名字即可继续使用。

Telegram是一款开源的即时通讯工具，以其极高的**开放性**、**安全性**著称。由于其本身完全开源，也为bot等应用提供了丰富的接口和SDK，将大大简化我们的开发流程。

如果最终决定移植至Telegram平台，我们将使用大家喜闻乐见的Python进行机器人的开发，也希望能提高大家的参与度。

如果没有意见的话，大家可以先安装注册Telegram进行体验。

**注：** Telegram在国内处于被墙状态。但由于校园网的特性（提供IPv6），在SJTU Wi-Fi网络环境下无需翻墙也可使用。但在寝室网络下，若路由器不支持IPv6，则需要翻墙使用。

**Comment by Uniblake** [comment]
能py那真是太好了h h h

**Comment by mayinghua** [comment]
这里花样好多。要围观
