### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by hebingchang** [SE407-2017/FinalProject-library-seats-reservation#16]
好消息，好消息，我们的项目已经支持**单元测试**啦！

### How-to
单元测试程序在`/tests`目录下，目前有两项测试：`PagesTest`与`ApiTest`。前者用于测试页面显示是否正常，后者用于测试应用程序接口是否正常工作。目前单元测试处于初级阶段，大家可以尝试加入各种复杂的测试项。

_推荐文档：_
（中文渣翻）http://laravelacademy.org/post/3274.html
（英文原版）https://laravel.com/docs/5.2/testing

### More
我们的单元测试接入了Travis-CI，每一次commit都会自动进行一次单元测试来评估代码可用性。大家可以在项目首页的readme文档里看到：
[![Build Status](https://travis-ci.org/SE407-2017/FinalProject-library-seats-reservation.svg?branch=master)](https://travis-ci.org/SE407-2017/FinalProject-library-seats-reservation)

↑这个就是项目的编译状态

（超好玩 大家快来玩啊）

**Comment by mayinghua** [comment]
看起来很好玩！没空玩，但还想看看怎么玩，你们写个详细点的介绍吧。。。。。。。。。。。如何？

**Comment by mayinghua** [comment]
laravel主页很cooooool

**Comment by hebingchang** [comment]
> 看起来很好玩！没空玩，但还想看看怎么玩，你们写个详细点的介绍吧。。。。。。。。。。。如何？

@mayinghua 好呀，写在项目报告里（

**Comment by hebingchang** [comment]
> laravel主页很cooooool

@mayinghua 是Web艺术家的框架了（
