### ISSUE TITLE
Good Ending

### ISSUE THREAD

**Issue by hebingchang** [SE407-2017/FinalProject-library-seats-reservation#18]
最后一个通知
-------------------------
项目结束了。最后一些功能上的改进最晚将在12月4日前完成。

-------------------------
从17-09-17到17-12-04，三个月的开发周期，我们共同完成了一个体量庞大（事实上只能算中小型，但对于我们来说已经非常复杂）的完整网站系统。对于你们来说，这可能是第一次用自己的代码，一字一句建立起数据流的交换，设计出具有艺术感的交互页面，仔细推敲展现给用户的文字。尽管我之前有一些开发经验，这仍是一次不可多得的练手机会；但更重要的是，与团队协作的能力得以提升。

- 感谢my wife @shinko1998 对于前端样式的巨大贡献与对于网站编程几乎从零开始的学习和强大的自学能力（以及对我的爱与支持）；
- 感谢 @taosiwen @linyx1998 妹子愿意花时间仔细阅读文档，在丝毫未向我询问的情况下独立完成了一些controller functions和views，为项目献出了自己的一份力，也同 @shinko1998 一起为我们组的男女比作出了杰出的贡献；
- 感谢项目经理 @Uniblake 想出如此有趣的idea使我们一同为之奋斗，也感谢其在我们陷入困境时慷慨同意修改项目计划；
- 感谢密院大佬 @HHJIMHHJ 出众的效率，尽管中途遇到了一些小问题，但也为项目的完善提供了不可或缺的力量；
- 感谢袁老板 @wy0102ylt 能够耐心地无基础学习开发。尽管Art Center很忙但也坚持来开组会，值得我们翘组会睡午觉的深刻反思与学习。
- 感谢 @mayinghua 老师在课程中教授关于需求分析、开发过程、设计和测试的知识，大大提升了开发效率与质量；
- 感谢助教 **苏宇** 老师抽空参加了我们的一次组会，并提出了宝贵的意见。

项目结束了，无论之后会不会再接触软件工程，学习之路无止境。希望大家`write the code, change the world`。

------------------------------
最后提醒大家，我们还要进行一次组内互评，另外大家的报告别忘了写，ddl在12月10日
之后想到什么再改

**Comment by mayinghua** [comment]
开心。说句老实话，我是什么也没有教的。
但每次看到同学们都在自我努力+团队合作中有很多收获，就再次感受到世界是属于未来的，你们的不断努力预示着未来的前景。
感谢大家的努力，让这一个学分总在闪烁不一样的光芒。

**Comment by Uniblake** [comment]
感觉还有很多要向组长学习😏

**Comment by linyx1998** [comment]
非常感谢组长对菜鸡的亲切关怀(；д；)

**Comment by shinko1998** [comment]
辛苦您了！为您打电话！

**Comment by taosiwen** [comment]
感谢组长全程carry🙋🏻🙋🏻🙋🏻

**Comment by wy0102ylt** [comment]
虽然很难还是学会了一点，灰常感谢组长！

**Comment by HangjiHe** [comment]
吼哇，资瓷
