### ISSUE TITLE
Regular meeting 4 (partly attended)

### ISSUE THREAD

**Issue by hebingchang** [SE407-2017/FinalProject-library-seats-reservation#6]
**汇报了已完成的子项目。**

Regular meeting 3的子项目已基本完成，由于部分同学确实有困难，临时进行了重新分工。

以下为新完成子项目：

ID | Name | Imp | Est (man-hour) | How to demo | Notes
-- | -- | -- | -- | -- | --
4 | 个人管理首页前端 | 50 | 5 | Jaccount登陆后直接跳转到该页面，     展示各种信息，详见Notes | 欢迎；现在有没有预约；今日已预约失败x次
6 | 预约选座服务前端 | 90 | 6 | 选择一个楼层，选择一张桌子进行预约；若用户已有预约或预约失败超限则拒绝预约 | 座位占用信息表     //浮夸的座位对应图（有空再画）     有插座则显示浮夸的插座图标
14 | 绑定微信号与Jaccount | 89 | 2 | 演示绑定 | 

由于这些子项目难度较高，暂时由我完成。大家如果感兴趣可以查看我的commits了解实现原理。
个人管理页面前端使用AngularJS框架，以便实现各页面的无缝衔接（懒加载）。由于个人管理页面前端框架已搭建完毕，剩余前端页面的开发将变得简单。**项目进度已过半，期中考试周过去后我们会考虑进行第二次分工。**

**Comment by mayinghua** [comment]
根据实际情况随时调整，你们做得很好

**Comment by hebingchang** [comment]
@mayinghua 谢谢老师，项目初期的确有一些问题没有考虑到额，调整项目也是为了能在规定时间内做出最好的效果。
