### ISSUE TITLE
Programming standard

### ISSUE THREAD

**Issue by hebingchang** [SE407-2017/FinalProject-library-seats-reservation#7]
## 编码规范
**变量命名**

- 下划线式：`$hello_world`, `$product_name`
- 纯小写
- 语义清晰：（反例）`$a`, `$b`, `$c`
- 避免全局变量，如果使用，全大写，如`UPPER_CASE`

**函数命名**

- 按函数功能
- 首单词首字母小写，后单词首字母大写
- 如: `function getReservationById() {...`

**缩进**

- 1个tab，4个空格

**括号先配对再写内容**

- 编辑器开启自动补全

**控制语句后空一格再写**

- `If`/`while`/`switch`等
- `if (a == 4)`

**控制语句中的表达式中操作符和变量分隔**

- （反例）`If ((4>a)&&(a+b>8))`
- `If ((4 > a) && (a + b > 8))`

**代码风格通用规则**

- （可选）函数左括号不用另起一行
- 函数之间使用空行分隔
- 一个函数的不同功能块之间使用空行分隔

**总是使用{}来表示区块**

- （反例）`If (a) a(); b();`
- `If (a) {a(); b();}`
- `If (a) {a();} b();`

**不要将目的不同的语句合成一行**
（反例）

- `get_text(document.getElementById(“my-div”))`
- `var a=b=0; var a=0,b=0;`
- `var a=(b+1),(c++),(d=c++);`

**编程风格通用规则**（参考，不强求）

- 提高代码的通用性
- 去耦合
- 减少重复，减少复制

**注释**

- 只在必要的地方加注释,减少无意义的注释
- 减少不明代码
- 注释不能代替代码可读性！

**最后**

- 别做无聊的优化
- 跟着团队风格写代码：自己和团队风格不统一，使用团队的风格

**Comment by mayinghua** [comment]
蛮简洁的。很好。

如果存在不是很明白的地方，大家一定多沟通。
